version: '3.0'

services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      DANGEROUSLY_DISABLE_HOST_CHECK: 'true'
    ports:
      - '${VITE_APP_PORT}:${VITE_APP_PORT}'
    command: 'npm run dev -- --port ${VITE_APP_PORT} --host'
    stdin_open: true
    volumes:
      - ./src:/usr/svelteapp/src
      - ./static:/usr/svelteapp/static
      - ./package.json:/usr/svelteapp/package.json
      - modules:/usr/svelteapp/node_modules
      - build:/usr/svelteapp/build
    restart: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${VITE_APP_PORT}']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 1s
    networks:
      - svelte

networks:
  svelte:
    driver: bridge

volumes:
  build:
  modules:
