name: app-lint-and-build-check

env:
  VITE_APP_PORT: 5757

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_lint_test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Clone app
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Run svelte check and lint
        run: |
          npm run check
          npm run lint

      - name: Run svelte check and lint
        run: npm run test
